### PR TITLE
Add integration with with Trackemon / Add log4net logging

### PR DESCRIPTION
**Pull request by ExcuseMi**
I added log4net so we can log on multiple levels and write to console & write to file.
The current way also has fancy colors.
image

### CODE REVIEW

**Comment by laincat** [comment]
[09:37:18][PKMN] Pokesnipers: Farfetchd at 35.6593675622,139.694846734 with unknown IV until 09:46:12
[09:37:22][PKMN] rare_pokemon_only: Snorlax at 38.177617974132,-122.25648221264 with unknown IV

未经处理的异常:  System.FormatException: 输入字符串的格式不正确。
   在 System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   在 System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   在 System.String.Format(String format, Object[] args)
   在 PogoLocationFeeder.Helper.Log.LogPokemonFormat(ILog log, String message, Object[] args) 位置 D:\Game\PogoLocationFeeder\PogoLocationFeeder\Helper\Log.cs:行号 90
   在 PogoLocationFeeder.Helper.Log.Pokemon(String message, String[] args) 位置 D:\Game\PogoLocationFeeder\PogoLocationFeeder\Helper\Log.cs:行号 56
   在 PogoLocationFeeder.Program.<feedToClients>d__11.MoveNext() 位置 D:\Game\PogoLocationFeeder\PogoLocationFeeder\Program.cs:行号 120
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 PogoLocationFeeder.Program.<relayMessageToClients>d__12.MoveNext() 位置 D:\Game\PogoLocationFeeder\PogoLocationFeeder\Program.cs:行号 129
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 PogoLocationFeeder.Program.<>c__DisplayClass13_0.<<Start>b__0>d.MoveNext() 位置 D:\Game\PogoLocationFeeder\PogoLocationFeeder\Program.cs:行号 149
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   在 System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   在 System.Threading.ThreadPoolWorkQueue.Dispatch()
   在 System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by IsBoris** [comment]
It works for me...

**Comment by IsBoris** [comment]
+1 tested on previous build, a must-have

**Comment by ExcuseMi** [comment]
@laincat the latest commit broke the code, should be fixed now

**Comment by Ilses** [comment]
Testing now

**Comment by IsBoris** [comment]
Trackemon API keeps timeouting.  Also `Error trying to get a sessionId for Trackemon:`

**Pull request merged**
