### PR TITLE
Add a view to the snipe area settings on the map

### PR DESCRIPTION
**Pull request by nicholashew**
Small feature for [917a066](https://github.com/5andr0/PogoLocationFeeder/commit/917a066445f32422be173e0023cf224a8a800678), a user can set the SW/NE latitude and longitude bounds area through the map instead of manually enter.
- Lat long bounds will be updated on google map idle event fired, implemented with WebBrowser. ObjectForScripting `System.Runtime.InteropServices`
-  Resize the windows application to get the rectangular area bounds

### GUI
screencap1

### Examples
screencap1

### CODE REVIEW

**Comment by ExcuseMi** [comment]
It would be great if when reopening it would go the already set location.

**Comment by ExcuseMi** [comment]
And sometimes, i get this error when exiting the application
image

**Comment by nicholashew** [comment]
I couldn't find a time to look into it. Seems like it has already fixed, is the issue still persist?

**Comment by ExcuseMi** [comment]
Yeah, I fixed it by adding it as resource. 
Also added reopening in the same spot. (it kinda a hit and miss with the zoom).

**Pull request merged**
